// Code generated by goctl. DO NOT EDIT.
package types

type EmailCodeRequest struct {
	Email string `json:"email"`
}

type EmailCodeResponse struct {
}

type InfoRequest struct {
	Identity string `json:"identity"`
}

type InfoResponse struct {
	UserName string `json:"username"`
	Email    string `json:email`
}

type LoginRequest struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}
